name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Manual Integration of Model (Glue Code Technical Debt)
      run: |
        python models.py

    - name: Setup BentoML
      uses: bentoml/setup-bentoml-action@v1.0.1
            

    - name: Build The Bento
      id: bento_build
      run: |
        bentoml build 
        bentoml list
